Migrate 25 crates to monorepo.
bytemuck_derive
hashlink
httparse
http-body
httpdate
idna
instant
intrusive-collections
itertools
jni-sys
lazy_static
libc
libloading
linked-hash-map
linkme
litrs
lock_api
log
lru-cache
lz4_flex
macaddr
managed
maybe-async
memchr
memoffset

Bug: 339424309
Test: treehugger
Change-Id: I6f6545eb832112d6fbf73f24b6632bdd13ae7121

error: external/rust/android-crates-io/crates/gbm/Android.bp:16:1: module "libgb
m_rust" variant "linux_glibc_x86_64_rlib_rlib-std": depends on //external/minigb
m:libgbm_sys which is not visible to this module
You may need to add "//external/rust/android-crates-io/crates/gbm" to its visibi
lity